services:
    db:
        image: mysql:8
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpass
            MYSQL_DATABASE: employees_db
            MYSQL_USER: springstudent
            MYSQL_PASSWORD: springpwd
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: employee_api_container
        depends_on:
            db:
                condition: service_started
                required: true
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/employees_db
            SPRING_DATASOURCE_USERNAME: springstudent
            SPRING_DATASOURCE_PASSWORD: springpwd
            SPRING_JPA_HIBERNATE_DDL_AUTO: update
        ports:
            - "8080:8080"

volumes:
    mysql_data:
